name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  run:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm i
      - run: npm run deploy
